trigger: 
  branches:
    include:
      - '*'

  paths:
    include:
      - dlwr.OOOScheduler.FrontEnd
pool:
  vmImage: ubuntu-latest

steps:
  
  - checkout: self
    submodules: true

    
  - task: NodeTool@0
    inputs:
      versionSpec: '16.x'
      displayName: 'Install Node.js'

  - task: Npm@1
    displayName: "npm install"
    inputs:
      command: 'install'
      workingDir: '$(System.DefaultWorkingDirectory)/dlwr.OOOScheduler.FrontEnd'
      verbose: true
      customCommand: 
  - task: Npm@1
    displayName: "npm install"
    inputs:
      command: 'custom'
      workingDir: '$(System.DefaultWorkingDirectory)/dlwr.OOOScheduler.FrontEnd'
      customCommand: 'run build'

  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: 'cd $(System.DefaultWorkingDirectory)/dlwr.OOOScheduler.FrontEnd && ls'
  - task: AzureStaticWebApp@0
    inputs:
      app_location: './dlwr.OOOScheduler.FrontEnd/dist'
      api_location: 'api'
      skip_app_build: true
      skip_api_build: true
      azure_static_web_apps_api_token: '$(deployment_token_swa)'
      config_file_location: './dlwr.OOOScheduler.FrontEnd'